#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Leatrix Plus 6.2.30 zhCN
# Leatrix Plus translation script
from __future__ import unicode_literals

# String replacement function
def ReplaceFunc(findReplacePairs):

	inF = open(filePath, "rb")
	fContent = unicode(inF.read(), "utf-8")
	inF.close()

	for pair in findReplacePairs:
		outText = fContent.replace(pair[0], pair[1])
		fContent = outText

	outF = open(newPath, "wb")
	outF.write(outText.encode("utf-8"))
	outF.close()
	return;

# Deckare old and new files
filePath = "Leatrix_Plus.lua"
newPath = "Leatrix_Plus_zhCN.lua"

# zhCN
findReplacePairs = [

	#You know, some of the text will replace the code together.
    ('"Frames"		, "LeaPlusNav6", "Frames"', '"框架"		, "LeaPlusNav6", "框架"'), 
    ('"RARE", "ELITE", "RARE ELITE"', '"稀有", "精英", "稀有精英"'), 
    ('SpellPanel, "Stack",', 'SpellPanel, "堆叠",'), 
    ('SpellPanel, "Pet",', 'SpellPanel, "宠物",'), 
    ('"Scale",', '"大小",'), 
    ('"Frames",', '"框架",'), 
    ('SetText("Player")', 'SetText("玩家")'), 
    ('SetText("Target")', 'SetText("目标")'), 
	#-------------------
	#-------------------
    ('"Zygor addon not found."', '"Zygor插件没有找到。"'), 
    ('"Memory Usage: "', '"内存使用："'), 
    ('"(calculating...)"', '"(计算中...)"'), 
    ('"You cannot do that in combat."', '"您不能在战斗中这么做。"'), 
    ('"plus"', '"++"'), 
    ('"."', '" 。"'), 
    ('"Settings"', '"设置"'), 
    ('"Select the settings that you want to use."', '"选择您想要使用的设置。"'), 
    ('"Click to configure the settings for this option."', '"点击设置此选项的设定。"'), 
	#-------------------
    ('"A cinematic skip was attempted."', '"已跳过过场动画。"'), 
    ('"A movie skip was attempted."', '"已跳过电影。"'), 
	#-------------------
    ('"Mission: "', '"任务："'), 
    ('"Ship Mission: "', '"舰队："'), 
    ('" Completed."', '" 完成。"'), 
    ('"Building: "', '"建设中："'), 
	#-------------------
    ('"Sell Junk Automatically"', '"自动售出垃圾"'), 
    ('"Show a summary of items sold"', '"显示物品售出简要"'), 
    ('"If checked, a brief summary will be shown in chat when items are sold automatically."', '"勾选：自动售出物品时，会在聊天窗口显示简要。"'), 
    ('"Show item links for items sold"', '"显示物品售出链接"'), 
    ('"If checked, item links will be shown in chat when items are sold automatically."', '"勾选：自动售出物品时，会在聊天窗口显示物品链接。"'), 
    ('"Sold "', '"售出 "'), 
    ('" item for "', '" 件物品获得 "'), 
    ('" items for "', '" 件物品获得 "'), 
	#-------------------
    ('"Repair Automatically"', '"自动修理"'), 
    ('"Repair using guild funds if available"', '"使用公会资金"'), 
    ("If checked, repair costs will be taken from guild funds for characters that are guilded and have permission to repair.\\n\\nIf the guilded character does not have permission to repair or not enough guild funds are available, the character's own funds will be used.", "勾选：如果角色在公会中允许使用公会修理，使用公会资金修理。\\n\\n如果此角色没有权限使用公会修理或者公会资金不足的话，则使用角色自身的资金。"), 
    ('"Show a brief summary of repair costs"', '"显示修理费用简要"'), 
    ('"If checked, a brief summary of repair costs will be shown in chat when an automatic repair is attempted."', '"勾选：自动修理时会在聊天粗口显示修理费用简要。"'), 
    ('"Repaired for "', '"修理费用 "'), 
    ('"The repair cost is "', '"修理费用为 "'), 
    ('".  You do not have enough money."', '" 。您没有足够的资金来修理。"'), 
    ('" (guild)."', '" (公会)。"'), 
    ('" (blind)."', '" (盲修)。"'), 
	#-------------------
    ('"Combat log cannot be hidden while undocked."', '"战斗记录未锁定时无法隐藏。"'), 
	#-------------------
    ('"Player Chain"', '"精英头像"'), 
    ('"Chain style"', '"头像风格"'), 
    ('"Choose a chain style for the player frame from the dropdown menu."', '"从下拉菜单中选择玩家头像风格。"'), 
	#-------------------
    ('"Class Colored Frames"', '"职业颜色框架"'), 
    ('"Show player frame in class color"', '"玩家框架职业颜色"'), 
    ('"If checked, the player frame background will be shown in class color."', '"勾选：玩家名称框架背景将显示为职业颜色。"'), 
    ('"Show target frame and focus frame in class color"', '"目标和焦点框架职业颜色"'), 
    ('"If checked, the target frame background and focus frame background will be shown in class color."', '"勾选：目标名称框架背景与焦点名称框架背景将显示为职业颜色。"'), 
	#-------------------
    ('"Spell Icons"', '"法术图标"'), 
    ('"Spell ID"', '"法术ID"'), 
    ('"Spell ID: "', '"法术ID："'), 
    ('"Show tooltips for the spell icons"', '"显示法术图标提示"'), 
    ('"If checked, tooltips for the spell icons will be shown when you hover over them."', '"勾选：当鼠标悬停在法术图标时会显示提示。"'), 
    ('"Show the spell ID in buff icon tooltips"', '"在增益图标提示中显示法术ID"'), 
    ('"If checked, spell IDs will be shown in the tooltips of beneficial spell icons (located in the buff frame and under the target frame)."', '"勾选：增益法术图标上的鼠标提示会显示法术ID。(位于增益框架或目标框架)。"'), 
    ('"Hide spell duration numbers (if enabled)"', '"隐藏法术持续时间(如果启用)"'), 
    ('"If checked, spell duration numbers will not be shown over the spell icons.\\n\\nIf unchecked, spell duration numbers will be shown over the spell icons if they are enabled in the game options panel (ActionBars menu)."', '"勾选：法术图标将不显示法术持续时间数字。\\n\\n未选：法术图标上将显示法术持续时间数字，如果选项在游戏选项面板中启用(动作条菜单)。"'), 
    ('"Layout"', '"布局"'), 
    ('"Anchor the spell icons to the player frame"', '"定位法术图标到玩家框架"'), 
    ('"If checked, spell icons will be shown above the player frame instead of the target frame.\\n\\nIf unchecked, spell icons will be shown above the target frame."', '"勾选：法术图标会取代目标框架显示在玩家框架上。\\n\\n未选：法术图标会显示在目标框架下。"'), 
    ('"Enter the spell IDs for the spell icons that you want to see.\\n\\nIf you want a spell icon to show only when the spell is stacked, enter the minimum stack size (otherwise leave it blank).\\n\\nIf a spell icon normally appears under the pet frame, check the pet checkbox."', '"输入您想要看见的法术图标的法术ID。\\n\\n如果您想要只有在法术堆叠时显示法术图标，请设置一个最小堆叠数(若不是请保持空置)。\\n\\n如果法术图标通常显示在宠物框架上，请勾选宠物复选框。"'), 
	#-------------------
    ('"Coordinates"', '"坐标"'), 
    ('"Show the coordinates frame"', '"显示坐标框架"'), 
    ('"If checked, the coordinates frame will be shown.\\n\\nIf you have the minimap button enabled, you can hold down SHIFT and right-click it to toggle this setting at any time.\\n\\nIf unchecked, the coordinates frame will be disabled and no CPU power will be allocated to updating it."', '"勾选：启用坐标框架。\\n\\n如果您有启用小地图按钮, 您可以在任何时候按住SHIFT+右键点击来切换此设定。\\n\\n未选：禁用坐标框架，减少CPU资源。"'), 
    ('"Darken the frame background"', '"显示背景"'), 
    ('"If checked, a dark background will be used for the frame."', '"勾选：坐标框架会有个深色背景。"'), 
    ('"Raise the frame strata level"', '"框架前置"'), 
    ('"If checked, the frame strata level will be set to HIGH allowing it to show on top of most frames.\\n\\nIf unchecked, the strata level will be set to MEDIUM."', '"勾选：坐标框架会显示在大部分框架之上。"'), 
    ('"Lock the frame and make it non-interactive"', '"锁定框架"'), 
    ("If checked, the frame will be locked and you will not be able to move it.\\n\\nEnabling this option will make the frame non-interactive, meaning you will be able to click through it as if it wasn't there.\\n\\nThis is useful if you are showing the coordinates in a space where you would normally click (such as the game world or minimap).", "勾选：锁定坐标框架使其不能移动。\\n\\n启用此选项将使坐标框架点击穿透。\\n\\n如果在您通常会点击的位置显示坐标(例如游戏世界或小地图)，这很有用。"), 
    ('"Drag the coordinates frame to position it.\\n\\nScale and style the frame using the settings on this page."', '"拖动坐标框架来定位它。\\n\\n框架的大小和风格在此页面设置。"'), 
	#-------------------
    ('"Minimap"', '"小地图"'), 
    ('"Merge tracking button with calendar button"', '"合并追踪与日历按钮"'), 
    ('"If checked, the minimap tracking button will be merged with the calendar button to save space.\\n\\nThe new tracking button will be moved to the space normally occupied by the calendar button.\\n\\nYou will be able to left-click the tracking button to show the tracking menu and right-click it to show the calendar."', '"勾选：小地图的追踪按钮将与日历按钮合并以节省空间。\\n\\n新的追踪按钮将移动到日历按钮通常占据的位置。\\n\\n您可以左键点击追踪按钮显示追踪菜单，右键点击它显示日历。"'), 
    ('"Hide zone information above the minimap"', '"隐藏小地图区域信息"'), 
    ('"If checked, the zone information shown above the minimap, as well as the world map button, will be hidden.\\n\\nThe tooltip for the tracking button will show zone text information instead.\\n\\nTo show the world map, press the map bind key (M by default)."', '"勾选：隐藏在小地图的区域信息和世界地图按钮。\\n\\n追踪按钮提示会被区域文本信息代替。\\n\\n按下地图绑定按键(默认M键)显示世界地图。"'), 
    ('"Hide the clock below the minimap"', '"隐藏小地图时间信息"'), 
    ('"If checked, the clock will be hidden."', '"勾选：时钟将隐藏。"'), 
    ('"Use the mousewheel to zoom in and out"', '"鼠标滚轮缩放小地图"'), 
    ('"If checked, you will be able to use the mousewheel to zoom in and out of the minimap.  The zoom in/out buttons will be hidden."', '"勾选：隐藏缩放按钮。您可以使用鼠标滚轮来缩放小地图。"'), 
    ('"Minimap scale"', '"小地图大小"'), 
    ('"Scale and style the minimap using the settings on this page.\\n\\nThis panel will close automatically if you enter combat."', '"小地图的大小和风格在此页面设置。\\n\\n如果您进入战斗此面板会自动关闭。"'), 
	#-------------------
    ('"Durability"', '"耐久"'), 
    ('"\\nOverall "', '"\\n整体 "'), 
    ('"You have "', '"您还有 "'), 
    ('" durability."', '" 耐久度。"'), 
	#-------------------
    ('"Hide Error Text"', '"隐藏错误信息"'), 
    ('"Show quest updates"', '"显示任务更新"'), 
    ('"If checked, quest updates will be shown in the error frame."', '"勾选：在错误框架显示任务更新。"'), 
    ('"Show important error text"', '"显示重要的错误信息"'), 
    ('"If checked, the following errors will be shown in the error frame:\\n\\n- Inventory full\\n- Quest log full\\n- Votekick alerts"', '"勾选：在错误框架中显示以下错误：\\n\\n- 背包已满\\n- 任务日志已满\\n- 投票踢人警报"'), 
	#-------------------
    ('"H"', '"头"'), 
    ('"C"', '"背"'), 
    ('"Helm"', '"头盔"'), 
    ('"Cloak"', '"披风"'), 
    ('"Tabard"', '"战袍"'), 
    ('"Nude"', '"果体"'), 
	#-------------------
    ('"Target Tracking Disabled"', '"关闭目标追踪"'), 
    ('"Target Tracking Enabled"', '"启用目标追踪"'), 
    ('"Coordinates Disabled"', '"关闭坐标"'), 
    ('"Coordinates Enabled"', '"启用坐标"'), 
    ('"Error frame text will be shown"', '"显示错误信息"'), 
    ('"Error frame text will be hidden"', '"隐藏错误信息"'),
	#------------------- 
    ('"Tooltip"', '"鼠标提示"'), 
    ('"Show guild ranks for your guild"', '"为您的公会显示公会等级"'), 
    ('"If checked, guild ranks will be shown for players in your guild."', '"勾选：显示在您的公会的玩家的公会等级。"'), 
    ("Show the unit's target", "显示单位的目标"), 
    ('"If checked, unit targets will be shown."', '"勾选：显示单位目标。"'), 
    ('"Color the backdrops based on faction"', '"阵营背景颜色"'), 
    ('"If checked, backdrops will be tinted blue (friendly) or red (hostile)."', '"勾选：背景会是蓝色(友好)或红色(敌对)。"'), 
    ('"Hide tooltips for world units during combat"', '"战斗中隐藏世界单位提示"'), 
    ('"If checked, tooltips for world units will be hidden during combat.\\n\\nYou can hold the shift key down to over-ride this setting."', '"勾选：在战斗中隐藏世界单位提示。\\n\\n您可以按住shift键来暂停这个设置。"'), 
    ('"Tooltip scale"', '"鼠标提示大小"'), 
    ('"Drag the tooltip overlay to position it.\\n\\nScale and style the tooltip using the settings on this page."', '"拖动鼠标提示框架定位。\\n\\n鼠标提示的大小和风格在此页面设置。"'), 
    ('"|cffff3333Level ??|cffffffff"', '"|cffff3333等级 ??|cffffffff"'), 
    ('"|cffff3333Level ??|cffffffff "', '"|cffff3333等级 ??|cffffffff "'), 
    ('"Not specified"', '"未指定"'), 
    ('"(Elite)"', '"(稀有)"'), 
    ('"|c00e066ff(Rare)"', '"|c00e066ff(精英)"'), 
    ('"|c00e066ff(Rare Elite)"', '"|c00e066ff(稀有精英)"'), 
    ('"(Boss)"', '"(首领)"'), 
    ('"|c12ff4400YOU"', '"|c12ff4400你"'), 
    ('"Target: "', '"目标："'), 
	#------------------- 4000
    ('"World Map"', '"世界地图"'), 
    ('"Show cursor coordinates at the top of the map"', '"在地图上显示鼠标坐标"'), 
    ('"If checked, cursor coordinates will be shown at the top of the map."', '"勾选：在地图顶端显示鼠标坐标。"'), 
    ('"Reveal unexplored areas"', '"全显未探索区域"'), 
    ('"Reveal unexplored areas of the map"', '"全显地图上未探索的区域"'), 
    ('"If checked, unexplored areas of the map will be revealed."', '"勾选：地图上未探索的区域会全部显示。"'), 
    ('"Show toggle checkbox at the top of the map"', '"在地图上显示切换复选框"'), 
    ('"If checked, a checkbox will be shown at the top of the map which will allow you to toggle unexplored areas directly from the map frame."', '"勾选：在地图顶端增加一个复选框，从而允许您直接从地图框架中切换未探索区域的显示。"'), 
    ('"Reveal"', '"全显"'), 
	#-------------------
    ('"Use Leatrix Plus to reset that frame."', '"使用Leatrix Plus重置此框架。"'), 
    ('"Use Leatrix Plus to move that frame."', '"使用Leatrix Plus移动此框架。"'), 
    ('"Overlay frames"', '"框架布局"'), 
    ('"Player frame"', '"玩家框架"'), 
    ('"Click to toggle the player frame overlay."', '"点击切换玩家框架的布局。"'), 
    ('"Target frame"', '"目标框架"'), 
    ('"Click to toggle the target frame overlay."', '"点击切换目标框架的布局。"'), 
    ('"World state frame"', '"世界状态框架"'), 
    ('"Click to toggle the world state frame overlay.\\n\\nThe world state frame is most commonly used for keeping score in PvP zones."', '"点击切换世界状态框架的布局。\\n\\n世界状态框架常用于PvP区域的记分。"'), 
    ('"Ghost frame"', '"灵魂框架"'), 
    ('"Click to toggle the ghost frame overlay.\\n\\nThe ghost frame appears when your character is a ghost.  It allows you to return to the spirit healer."', '"点击切换灵魂框架的布局。\\n\\n当您的角色变成灵魂的时候灵魂框架才会出现。它可以让您返回灵魂医者。"'), 
    ('"Mirror timer bar frame"', '"计时条框架"'), 
    ('"Click to toggle the mirror timer bar overlay.\\n\\nThe mirror timer bar is used for activities such as underwater breathing.\\n\\nNote that not all timer bars use this frame."', '"点击切换镜像计时条的布局。\\n\\n镜像计时条用于各种活动，如水下呼吸。\\n\\n注意不是所有的计时器条使用此框架。"'), 
    ('"Selected frame scale"', '"选择框架大小"'), 
    ('"Drag the frame overlays to position the frames.  You can toggle the overlays using the checkboxes on this page.\\n\\nTo change the scale of a frame, click it to select it then adjust the scale slider.\\n\\nThis panel will close automatically if you enter combat."', '"拖动框架定位。您可以在此页面上切换复选框。\\n\\n要改变框架大小，单击将其选定，然后调节大小滑块。\\n\\n如果您进入战斗此面板会自动关闭。"'), 
    ('"World State"', '"世界状态"'), 
    ('"Timer"', '"计时条"'), 
    ('"Ghost"', '"灵魂"'), 
	#-------------------
    ('"Combat Plates"', '"战斗姓名板"'), 
    ('"Unit types"', '"单位类型"'), 
    ('"Pets"', '"宠物"'), 
    ('"If checked, pet nameplates will be shown during combat."', '"勾选：在战斗中显示敌方宠物的姓名版。"'), 
    ('"Guardians"', '"守卫"'), 
    ('"If checked, guardian nameplates will be shown during combat."', '"勾选：在战斗中显示敌方守卫的姓名版。"'), 
    ('"Totems"', '"图腾"'), 
    ('"If checked, totem nameplates will be shown during combat."', '"勾选：在战斗中显示敌方图腾的姓名版。"'), 
    ('"Minor enemies"', '"小怪"'), 
    ('"If checked, minor enemy nameplates will be shown during combat."', '"勾选：在战斗中显示敌方小怪的姓名版。"'), 
    ('"Nameplate coloring"', '"姓名版颜色"'), 
    ('"Show nameplates in class color"', '"职业颜色"'), 
    ('"If checked, enemy nameplates will be shown in class color."', '"勾选：敌方姓名版使用职业的颜色。"'), 
    ('"Select the settings that you want to use.\\n\\nThis panel will close automatically if you enter combat."', '"选择您想要使用的设置。\\n\\n如果您进入战斗此面板会自动关闭。"'), 
	#-------------------
    ('"Viewport"', '"窗口"'), 
    ('"Top Border"', '"顶部边框"'), 
    ('"Bottom Border"', '"底部边框"'), 
    ('"Left Border"', '"左侧边框"'), 
    ('"Right Border"', '"右侧边框"'), 
    ('"Options"', '"选项"'), 
    ('"Resize the game world"', '"调整游戏世界"'), 
    ('"If checked, the game world will be resized to fit between the top and bottom borders.\\n\\nThis ensures that none of the game world is blocked by those borders.\\n\\nThis setting has no effect on the left and right borders."', '"勾选：游戏世界将被适应调整在顶部和底部的边框之间。\\n\\n这确保游戏世界不会被这些边框阻断。\\n\\n此设置对左侧和右侧的边框没有影响。"'), 
    ('"Drag the sliders to set the size of the viewport borders."', '"拖动滑块设置窗口边框的大小。"'), 
	#-------------------
    ('"Roles Button"', '"角色按钮"'), 
    ('"Show active talent specialisation in chat"', '"在聊天窗口显示激活的天赋专精"'), 
    ('"If checked, your active talent specialisation will be shown in chat when you login and when you switch specs."', '"勾选：当您登录或切换专精，会在聊天窗口显示您激活的天赋专精。"'), 
    ('"Show Dungeon Finder roles in chat"', '"在聊天窗口显示地下城查找器的角色"'), 
    ('"If checked, your saved Dungeon Finder roles will be shown in chat when you login and when you switch specs."', '"勾选：当您登录或切换专精，会在聊天窗口显示您保存的地下城查找器角色。"'), 
    ('"Your active specialisation is "', '"您启用的专精是 "'), 
    ('"Primary"', '"主要"'), 
    ('"Secondary"', '"第二"'), 
    ('"primary spec"', '"主要专精"'), 
    ('"secondary spec"', '"第二专精"'), 
    ('"Your Dungeon Finder role is"', '"您的地下城寻求器角色类型是"'), 
    ('"Your Dungeon Finder roles are"', '"您的地下城寻求器角色类型是"'), 
    ('"Save Roles"', '"保存角色"'), 
    ('"Your selected roles have been saved to your "', '"您所选择的角色类型已保存到您的 "'), 
    ('"Click to save your selected group roles to your current talent spec.\\n\\nYour saved roles will be selected automatically when you switch specs."', '"点击保存选定的团队角色类型到您当前的天赋。\\n\\n当您切换天赋时将自动选择保存的角色类型。"'), 
	#-------------------
    ('"Class Colors"', '"职业颜色"'), 
    ('"Use class colors in local channels"', '"本地频道使用职业颜色"'), 
    ('"If checked, class colors will be used in local channels (such as say, party, raid, etc)."', '"勾选：在本地频道的名称将依职业颜色 (如：说、队伍、团队、等)。"'), 
    ('"Use class colors in global channels"', '"全区频道使用职业颜色"'), 
    ('"If checked, class colors will be used in global channels (such as general, trade, etc)."', '"勾选：在全区频道的名称将依职业颜色 (如：综合、交易、等)。"'), 
    ('"Max"', '"最大"'), 
    ('"Buyout Only"', '"只限直购"'), 
    ('"Gold Only"', '"只限金币"'), 
    ('"Find"', '"查找"'), 
    ('"To use the Find button, you need to deselect the Game Time filter."', '"使用查找按钮，需要取消选择游戏时间筛选。"'), 
    ('"A friend request from "', '"好友 "'), 
    ('" was automatically declined."', '" 的邀请已被自动拒绝。"'), 
	#-------------------
    ('"Accept Resurrection"', '"接受复活"'), 
    ('"Exclude combat resurrection requests"', '"不包括战斗中的复活请求"'), 
    ('"If checked, resurrection requests will not be automatically accepted if the player resurrecting you is in combat."', '"勾选：当您处于战斗状态时不会自动接受复活。"'), 
    ('"Thank the player who resurrected you"', '"自动感谢"'), 
    ('"If checked, your character will emote a thank you when a resurrection is automatically accepted."', '"勾选：当复活自动接受时，您的角色将会 /感谢 复活您的人。"'), 
	#-------------------
    ('"Automate Quests"', '"自动任务"'), 
    ('"Accept and turn-in quests automatically"', '"自动接受与提交任务"'), 
    ('"If checked, quests will be accepted and turned-in automatically.\\n\\nYou can hold the shift key down when you talk to a quest giver to over-ride this setting."', '"勾选：自动接受与提交任务。\\n\\n您可以在任务给予者交谈时按住Shift以暂停此设置。"'), 
    ('"Select quests automatically"', '"自动选择任务"'), 
    ('"If checked, quests will be selected automatically when you talk to a quest giver.\\n\\nYou can hold the shift key down when you talk to a quest giver to over-ride this setting."', '"勾选：您与任务给予者交谈时，会自动选择任务。\\n\\n您可以在任务给予者交谈时按住Shift以暂停此设置。"'), 
    ('"Select gossip automatically"', '"自动选择互动"'), 
    ('"If checked, gossip will be selected automatically if only one gossip option is being offered.\\n\\nYou can hold the shift key down when you talk to a quest giver to over-ride this setting."', '"勾选：只有一个互动选项时，会自动选择互动。\\n\\n您可以在任务给予者交谈时按住Shift以暂停此设置。"'), 
	#-------------------
    ('"Release in PvP Zones"', '"PvP区域自动释放"'), 
    ('"Automatic release zones"', '"自动释放区域"'), 
    ('"Battlegrounds"', '"战场"'), 
    ('"If checked, you will release automatically after you die in a battleground."', '"勾选：您在战场死后会自动释放尸体。"'), 
    ('"Wintergrasp"', '"冬拥湖"'), 
    ('"If checked, you will release automatically after you die in Wintergrasp."', '"勾选：您在冬拥湖死后会自动释放尸体。"'), 
    ('"Tol Barad (the PvP zone)"', '"托尔巴拉德(PvP区域)"'), 
    ('"If checked, you will release automatically after you die in Tol Barad (the PvP zone)."', '"勾选：您在托尔巴拉德(PvP区域)死后会自动释放尸体。"'), 
    ('"Ashran"', '"阿什兰"'), 
    ('"If checked, you will release automatically after you die in Ashran."', '"勾选：您在阿什兰死后会自动释放尸体。"'), 
    ('"Select the zones where automatic release should operate."', '"选择想要自动释放尸体生效的区域。"'), 
	#-------------------
    ('"Invite from Whispers"', '"密语邀请"'), 
    ('"Whisper keyword"', '"密语关键字"'), 
    ('"Enter the keyword that you want to use."', '"输入您想使用的关键字。"'), 
    ('"If checked, a group invite will be automatically sent to anyone who whispers a designated keyword to you.\\n\\nYou need to be either ungrouped or party leader in your own group for this to work.\\n\\nYou can change the keyword by clicking the configuration button to the right.\\n\\nKeyword: |cffffffff"', '"勾选：队伍邀请将会自动发送到每个密语指定关键字给您的人。\\n\\n您需要队长或团队助理在您的队伍以使此工作。\\n\\n您可以通过点击右恻配置按钮改变关键字。\\n\\n关键字: |cffffffff"'), 
	#-------------------
    ('"Reset"', '"重置"'), 
    ('"Click to reset the settings on this page."', '"点击重置此页的设定。"'), 
    ('"Help"', '"帮助"'), 
    ('"No help is available for this page."', '"此页没有可用的帮助讯息。"'), 
    ('"Back to Main Menu"', '"返回主选单"'), 
    ('"Click to return to the main menu."', '"点击返回主选单。"'), 
    ('"Reload"', '"重载"'), 
    ('"Configuration Panel"', '"配置面板"'), 
    ('"Version "', '"版本 "'), 
    ("Your UI needs to be reloaded for some of the changes to take effect.\\n\\nYou don't have to click the reload button immediately but you do need to click it when you are done making changes and you want the changes to take effect.", "您的界面需要重新载入来使一些更改生效。\\n\\n您不必立即点击重新载入按钮，当您完成更改并且希望更改生效时需要点击它。"), 
    ('"Your UI needs to be reloaded."', '"您的界面需要重载。"'), 
    ('"Panel position has been reset."', '"面板位置已被重置。"'), 
    ('"You have no rested bubbles."', '"您没有休息泡泡。"'), 
    ('"You have "', '"您还有 "'), 
    ('" rested bubbles."', '" 休息泡泡。"'), 
    ('"Dark Soil scanning activated.  Reload UI to exit."', '"深色土壤扫描已激活。重启界面以退出。"'), 
    ('"Dark Soil scanning is already activated.  You only need to run this once.  Reload UI to exit."', '"深色土壤扫描已经被激活。您只需要运行一次此。重启界面以退出。"'), 
    ('"Shaders: "', '"着色器："'), 
    ('"Particle density: |cffffffff"', '"粒子密度：|cffffffff"'), 
    ('"Weather density: |cffffffff"', '"天气密度：|cffffffff"'), 
    ('"SynchroniseConfig: |cffffffff"', '"同步配置：|cffffffff"'), 
    ('"[Unnamed Frame: %s]"', '"[未命名框架: %s]"'), 
	#-------------------
    ('"Home"', '"首页"'), 
    ('"Automation"', '"自动"'), 
    ('"Blocking"', '"拒绝"'), 
    ('"Chat"', '"聊天"'), 
    ('"Text"', '"文字"'), 
    ('"Interface"', '"介面"'), 
    ('"System"', '"系统"'), 
	#-------------------
    ('"Welcome to Leatrix Plus."', '"欢迎来到 Leatrix Plus"'), 
    ('"To begin, choose an options page."', '"请选择一个选项页面来开始。"'), 
    ('"Support"', '"支援"'), 
    ('"Tip"', '"提示"'), 
    ("Click |TInterface\\\\WorldMap\\\\Gear_64.png:20:20:0:0:32:32:0:16:0:16|t buttons to access additional configuration options.", "点击 |TInterface\\\\WorldMap\\\\Gear_64.png:20:20:0:0:32:32:0:16:0:16|t 按钮进行进阶设置选项。"), 
	#-------------------
    ('"Character"', '"角色"'), 
    ('"Automate quests*"', '"自动任务*"'), 
    ('"If checked, quests will be selected, accepted and turned-in automatically.\\n\\nYou can hold the shift key down when you talk to a quest giver to over-ride this setting.\\n\\n* Requires UI reload."', '"勾选：任务选择会自动接受与提交。\\n\\n您可以在任务给予者交谈时按住Shift以暂停此设置。\\n\\n* 需要重载界面。"'), 
    ('"Automate gossip*"', '"自动互动*"'), 
    ('"If checked, gossip will be selected automatically if only one gossip option is being offered.\\n\\nYou can hold the shift key down when you open a gossip window to over-ride this setting.\\n\\n* Requires UI reload."', '"勾选：互动只有一项时会自动选择。\\n\\n您可以在开启互动窗口时按住Shift以暂停此设置。\\n\\n* 需要重载界面。"'), 
    ('"Release in PvP zones"', '"战场释放"'), 
    ('"If checked, you will release automatically after you die in a designated PvP zone.\\n\\nYou can select zones by clicking the configuration button to the right.\\n\\nYou will not release automatically if you have the ability to self-resurrect (soulstone, reincarnation, etc)."', '"勾选：在选定的PvP区域死亡后会自动释放尸体。\\n\\n您可以点击右侧的设置按钮选择区域。\\n\\n您将不会自动释放如果您有技能来自复活(灵魂石、复生、等)。"'), 
    ('"Accept resurrection"', '"接受复活"'), 
    ('"If checked, summon requests will be accepted automatically unless you are in combat."', '"勾选：自动接受召唤请求，除非您在战斗中。"'), 
    ('"Accept summon"', '"接受召唤"'), 
    ('"If checked, resurrection requests will be accepted automatically.\\n\\nYou can configure this option by clicking the configuration button to the right."', '"勾选：自动接受复活请求。\\n\\n您可以点击右侧的设置按钮配置此选项。"'), 
    ('"Vendors"', '"商人"'), 
    ('"Sell junk automatically*"', '"自动售出垃圾*"'), 
    ('"If checked, all grey items in your bags will be sold automatically when you visit a merchant.\\n\\nYou can hold the shift key down when you talk to a merchant to over-ride this setting.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：当您访问商店时所有背包内的灰色物品会自动售出。\\n\\n您可以在与商店NPC对话时按下shift键暂停此设定。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Repair automatically*"', '"自动修理装备*"'), 
    ('"If checked, your gear will be repaired automatically when you visit a suitable merchant.\\n\\nYou can hold the shift key down when you talk to a merchant to over-ride this setting.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：当您访问可修理的商店时所有的装备都会被自动修理。\\n\\n您可以在与商店NPC对话时按下shift键暂停此设定。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Groups"', '"团队"'), 
    ('"Party from friends"', '"接受好友队伍邀请"'), 
    ('"If checked, party invitations from friends will be automatically accepted unless you are queued in Dungeon Finder."', '"勾选：自动接受好友发出的队伍邀请，除非您正在地下城或团队搜寻器队列中。"'), 
    ('"Queue from friends"', '"自动接受好友队列"'), 
    ('"If checked, requests initiated by your party leader to join the Dungeon Finder queue will be automatically accepted if the party leader is in your friends list.\\n\\nEnabling this option does not port you into the dungeon automatically.\\n\\nThis option requires that you have selected a role for your character in the Dungeon Finder window."', '"勾选：自动接受地下城或团队的队列，如果领队是在您的好友名单中。\\n\\n启用此选项并不会自动传送您到地下城。\\n\\n此选项需要您有在地下城寻求器中预先选好角色的类型。"'), 
    ('"Group from premades"', '"预设队伍"'), 
    ('"If checked, premade group invitations (for premade groups that you are signed up for) will be automatically accepted."', '"勾选：自动接受预设队伍邀请(对于已预设过的队伍)。"'), 
    ('"Invite from whispers"', '"密语邀请"'), 
    ('"This tooltip is replaced by the option code"', '"这个提示被替换为选项代码"'), 
	#-------------------
    ('"Duels"', '"决斗"'), 
    ('"Block duels"', '"拒绝决斗"'), 
    ('"If checked, duel requests will be blocked unless the player requesting the duel is in your friends list."', '"勾选：决斗请求将被屏蔽，除非发起的玩家在好友名单内。"'), 
    ('"Block pet battle duels"', '"拒绝宠物对战"'), 
    ('"If checked, pet battle duel requests will be blocked unless the player requesting the duel is in your friends list."', '"勾选：宠物对战请求将被屏蔽，除非发起的玩家在好友名单内。"'), 
    ('"Social"', '"社交"'), 
    ('"Block party invites"', '"拒绝队伍邀请"'), 
    ('"If checked, party invitations will be blocked unless the player inviting you is in your friends list."', '"勾选：队伍邀请将被屏蔽，除非邀请的玩家在好友名单内。"'), 
    ('"Block friend requests"', '"阻止好友请求"'), 
    ('"If checked, BattleTag and Real ID friend requests will be automatically declined.\\n\\nEnabling this option will automatically decline any pending requests."', '"勾选：BattleTag 与 实名ID 好友请求将被自动拒绝。\\n\\n启用这个选项将会自动拒绝任何待定的请求。"'), 
    ('"Trade and Guild"', '"交易和公会"'), 
    ('"Manage trade and guild*"', '"管理交易和公会*"'), 
    ("If checked, you will be able to configure trade and guild invitation blocking using the two settings below.\\n\\nThese are replacements for the game options panel settings ('Controls' menu) to make them work account-wide.\\n\\n* Requires UI reload.  After the reload, the checkbox controls below will be available.", "勾选：您可以使用下面两个设置来启用或禁用拒绝交易请求以及拒绝公会邀请与签名。\\n\\n 这会替代暴雪选项面版的设置(控制菜单)并让它为帐号通用。\\n\\n* 需要重载界面。重载之后，下方的两个复选框才能使用。"), 
    ('"Block trade requests"', '"拒绝交易请求"'), 
    ('"If checked, trade requests will be blocked."', '"勾选：交易请求将被屏蔽。"'), 
    ('"Block guild invites"', '"拒绝公会邀请"'), 
    ('"If checked, guild invitations and petitions will be blocked."', '"勾选：公会邀请与公会申请签名将被屏蔽。"'), 
	#-------------------
    ('"Chat Frame"', '"聊天框架"'), 
    ('"Use easy resizing*"', '"使用简易缩放*"'), 
    ('"If checked, dragging the General chat tab while the chat frame is locked will expand the chat frame upwards.\\n\\n\If the chat frame is unlocked, dragging the General chat tab will move the chat frame.\\n\\n* Requires UI reload."', '"勾选：当聊天框架锁定时拖动综合聊天标签可以将聊天框往上扩展。\\n\\n\如果聊天框架未锁定，拖动综合聊天标签将会移动整个框架。\\n\\n* 需要重载界面。"'), 
    ('"Hide the combat log*"', '"隐藏战斗记录*"'), 
    ('"If checked, the combat log will be hidden.\\n\\nThe combat log must be docked in order for this option to work.\\n\\nIf the combat log is undocked, you can dock it by dragging the tab (and reloading your UI) or by resetting the chat windows (from the chat menu).\\n\\n* Requires UI reload."', '"勾选：隐藏战斗记录。\\n\\n注意此选项不会关闭战斗记录的功能所以伤害统计插件仍将正常工作。\\n\\n战斗记录需要是非卸除状态此选项才能作用。 如果战斗记录已卸除(独立显示)，您需要拖动标签来停靠(并且重载您的界面)或是重置聊天窗口的设定 (从聊天选单)。\\n\\n* 需要重载界面。"'), 
    ('"Hide chat buttons*"', '"隐藏聊天按钮*"'), 
    ('"If checked, chat frame buttons will be hidden.\\n\\nClicking chat tabs will automatically show the latest messages.\\n\\nUse the mouse wheel to scroll through the chat history.  Hold down SHIFT for page jump or CTRL to jump to the top or bottom of the chat history.\\n\\nEnabling this option also enables the mouse scrolling option in the game options panel (social menu) and prevents you from changing it.\\n\\n* Requires UI reload."', '"勾选：隐藏聊天框按钮。\\n\\n点击聊天标签将自动显示最后的讯息。\\n\\n您可以使用鼠标滚轮来滚动聊天的历史记录。\\n\\n滚动时，您可以按住Shift来一次滚动一页，或按住Crtl直接跳到聊天历史记录的开头或结尾。\\n\\n启用此选项会同时启用暴雪滑鼠滚轮选项(社交选项)并且防止您改变它。\\n\\n* 需要重载界面。"'), 
    ('"Unclamp chat frame*"', '"松开聊天框架*"'), 
    ('"If checked, you will be able to drag the chat frame to the edge of the screen.\\n\\n* Requires UI reload."', '"勾选：聊天框将不再限制在屏幕内。\\n\\n这允许您移动聊天框到屏幕边缘(或超过)。\\n\\n* 需要重载界面。"'), 
    ('"Move editbox to top*"', '"移动输入框到顶部*"'), 
    ('"If checked, the editbox will be moved to the top of the chat frame.\\n\\n* Requires UI reload."', '"勾选：聊天输入框将被移动到聊天框架的顶部。\\n\\n* 需要重载界面。"'), 
    ('"Mechanics"', '"调整工具"'), 
    ('"Disable sticky chat*"', '"使用经典聊天样式*"'), 
    ('"If checked, sticky chat will be disabled.\\n\\nNote that this does not apply to temporary chat windows or Battle.net conversations.\\n\\n* Requires UI reload."', '"勾选：粘性聊天将被禁用。\\n\\n注意，这并不适用于临时聊天窗口或战网对话。\\n\\n* 需要重载界面。"'), 
    ('"Use arrow keys in chat*"', '"聊天框中用方向键*"'), 
    ('"If checked, you can press the arrow keys to move the insertion point left and right in the chat frame.\\n\\nIf unchecked, the arrow keys will use the default keybind setting.\\n\\n* Requires UI reload."', '"勾选：您可以在聊天框中按箭头键左右移动插入点。\\n\\n未选：方向键将使用预设绑定的设定。\\n\\n* 需要重载界面。"'), 
    ('"Disable chat fade*"', '"取消聊天内容淡出*"'), 
    ('"If checked, chat text will not fade out after a time period.\\n\\n* Requires UI reload."', '"勾选：聊天的文字不会在一段时间后淡出。\\n\\n* 需要重载界面。"'), 
    ('"Increase chat history*"', '"增加聊天历史记录*"'), 
    ('"If checked, your chat history will increase to 4096 lines.  If unchecked, the default will be used (128 lines).\\n\\nEnabling this option may prevent some chat text from showing during login.\\n\\n* Requires UI reload."', '"勾选：您的聊天记录将被增加到4096行。如果未勾选，将使用预设(128行).\\n\\n启用此选项可能会在登入过程中阻止一些聊天的文字显示。\\n\\n* 需要重载界面。"'), 
    ('"Chat Colors"', '"聊天颜色"'), 
    ('"Universal group color*"', '"通用团队颜色*"'), 
    ('"If checked, raid chat and instance chat will both be colored blue (to match the default party chat color).\\n\\n* Requires UI reload."', '"勾选：团队聊天与副本频道将同时设定为队伍频道的颜色(预设为蓝色)。\\n\\n* 需要重载界面。"'), 
    ('"Use class colors in chat*"', '"聊天职业颜色*"'), 
    ('"If checked, class colors will be used in the chat frame.\\n\\n* Requires UI reload."', '"勾选：聊天框架会使用职业颜色。\\n\\n* 需要重载界面。"'), 
	#-------------------
    ('"Zone Text"', '"区域文本"'), 
    ('"Hide zone text*"', '"隐藏区域文本*"'), 
    ("If checked, zone text will not be shown (eg. 'Ironforge').\\n\\n* Requires UI reload.", "勾选：区域文本将不会显示 (如：铁炉堡)\\n\\n* 需要重载界面。"), 
    ('"Hide subzone text*"', '"隐藏子区文本*"'), 
    ("If checked, subzone text will not be shown (eg. 'Mystic Quarter').\\n\\n* Requires UI reload.", "勾选：子区域文本将不会显示(如：秘法区)。\\n\\n* 需要重载界面。"), 
    ('"Combat Text"', '"战斗文本"'), 
    ('"Hide portrait text*"', '"隐藏头像上数字*"'), 
    ('"If checked, damage and healing numbers in the player and pet portrait frames will be hidden.\\n\\n* Requires UI reload."', '"勾选：在玩家与宠物的头像框架上的伤害与治疗数字将不会显示。\\n\\n* 需要重载界面。"'), 
    ('"Error Text"', '"错误文本"'), 
    ('"Hide error text*"', '"隐藏错误信息*"'), 
    ("If checked, error messages (such as 'Not enough rage') will not be shown.\\n\\nIf you have the minimap button enabled, you can right-click it to toggle error messages without affecting this setting.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right.", "勾选：错误信息(例如：缺少怒气)将不会显示。\\n\\n如果您有启用小地图按钮，您可以用鼠标右键单击它来切换，而不会影响此设置\\n\\n* 需要重载界面。 重载之后，配置按钮才能使用。"), 
    ('"Mail Text"', '"邮件文本"'), 
    ('"Resize mail text*"', '"调整邮件文本*"'), 
    ('"If checked, standard mail text will be resized to the slider value below.\\n\\nThis does not affect mail created using templates (such as auction house invoices).\\n\\n* Requires UI reload.  After the reload, the slider control below will be available."', '"勾选：标准邮件文本将被调整为下方滑块值。\\n\\n这不会影响使用模板（如拍卖行清单）的邮件。\\n\\n* 需要重载界面。 重载之后，下方的滑块控制才能使用。"'), 
    ('"Quest Detail Text"', '"任务日志"'), 
    ('"Resize quest detail text*"', '"调整任务日志文本*"'), 
    ('"If checked, quest detail text will be resized to the slider value below.\\n\\nEnabling this option will also change the text size on other frames which inherit the same font (such as the Dungeon Finder frame).\\n\\n* Requires UI reload.  After the reload, the slider control below will be available."', '"勾选：任务日志文本将被调整为下方滑块值。\\n\\n启用此选项也将同时影响使用同字型的其它框架文字大小(如地城寻求器框架)。\\n\\n* 需要重载界面。 重载之后，下方的滑块控制才能使用。"'), 
	#-------------------
    ('"Enhancements"', '"增强功能"'), 
    ('"Enhance world map*"', '"增强世界地图*"'), 
    ('"If checked, you will be able to reveal unexplored areas of the map and show cursor coordinates at the top of the map.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您将可以显示地图未探索区域，并且在地图顶部显示鼠标坐标。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Customise minimap*"', '"自定义小地图*"'), 
    ('"If checked, you will be able to customise and rescale the minimap.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您可以自订小地图的一些功能例如改变大小以及各种小地图的元件。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Manage tooltip*"', '"管理鼠标提示*"'), 
    ('"If checked, the tooltip will be color coded and you will be able to modify the tooltip layout and scale.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：鼠标提示将会使用颜色编码并且您将能够修改鼠标提示的布局和缩放。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Controls"', '"控制"'), 
    ('"Show vanity controls*"', '"显示梳妆控制*"'), 
    ('"If checked, two checkboxes will be added to the character sheet to allow you to toggle your helm and cloak easily.\\n\\nThe checkboxes can be placed in either of two locations on the character sheet.  To toggle between them, hold down SHIFT and right-click either checkbox.\\n\\nNote that there is a small delay after clicking a checkbox before it takes effect.  If you toggle the checkboxes too quickly, they may seem to stop working.  If that happens, just wait a few seconds.\\n\\n* Requires UI reload."', '"勾选：在角色属性窗口添加两个复选框，让您可以容易切换您的头盔和披风的显示。\\n\\n当您的角色死亡的时候这些复选框是无法点击的。\\n\\n此框可以放在角色窗口中两个位置中的任何一个位置上，要切换位置，只要在框上按下Shift+右键。\\n\\n注意：点击一个复选框后生效之前，有一个小的延迟。\\n\\n如果您切换复选框太过迅速，他们可能会停止作用，如果发生这种情形，只要等候几秒即可。\\n\\n* 需要重载界面。"'), 
    ('"Show volume slider*"', '"显示音量滑块*"'), 
    ('"If checked, a master volume slider will be shown on the character sheet.\\n\\nThe volume slider can be placed in either of two locations on the character sheet.  To toggle between them, hold down SHIFT and right-click it.\\n\\n* Requires UI reload."', '"勾选：在角色属性窗口添加一个主音量的滑动模块。\\n\\n此音量控制可以放在角色窗口两个位置中的任何一个位置，要切换位置，只要在它上面按下Shift+右键。\\n\\n* 需要重载界面。"'), 
    ('"Show auction controls*"', '"显示拍卖附加*"'), 
    ('"If checked, additional functionality will be added to the auction house.\\n\\nBuyout only - create buyout auctions without filling in the starting price.\\n\\nGold only - set the copper and silver prices at 99 to speed up new auctions.\\n\\nFind - search the auction house for the item you are selling.\\n\\nIn addition, the auction duration setting will be saved account-wide.\\n\\n* Requires UI reload."', '"勾选：拍卖行框架添加额外的功能。\\n\\n只限直购 - 使您能够创建一口价拍卖而无需填写起始价格。\\n\\n只限金币 - 使您能够永久设置银与铜的价格在99以加快新的拍卖。\\n\\n查找 - 使您能够简单的搜寻拍卖场中您拍卖的物品。\\n\\n此外, 拍卖时间的设置将被保存为帐号通用。\\n\\n* 需要重载界面。"'), 
    ('"Show dressup buttons*"', '"显示试衣按钮*"'), 
    ('"If checked, two buttons will be added to the dressup frame which will allow you to hide your tabard or appear nude.\\n\\n* Requires UI reload."', '"勾选：在试衣间添加两个按钮，允许您隐藏战袍或果体。\\n\\n* 需要重载界面。"'), 
    ('"Show roles button*"', '"显示角色按钮*"'), 
    ('"If checked, a button will be added to the Dungeon Finder window which will allow you to save your currently selected group roles to your talent spec.\\n\\nThese roles will then be selected automatically when you switch specs.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：在地城寻求窗口添加一个按钮，这将让您保存当前选定的团体角色类型到您的天赋。\\n\\n当您切换天赋时将会自动选择这些角色类型。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Information"', '"信息"'), 
    ('"Show coordinates*"', '"显示坐标框架*"'), 
    ("If checked, coordinates representing your character's location will be shown in a movable, customisable frame.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right.", "勾选： 在一个可移动与自订化的框架中显示您角色位置的坐标。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"), 
    ('"Show spell icons*"', '"显示法术图标*"'), 
    ('"If checked, you will be able to place up to five beneficial spell icons above the target or player frame.\\n\\nThis option is designed for watching spell cooldowns (such as Mend Pet or Ice Barrier).\\n\\nEnabling this option will prevent you from placing buffs above the target frame.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选： 您将能够把多达五个有益法术图标放在目标或玩家框架上。\\n\\n这个选项是设计用来监视法术冷却(像是猎人的治疗宠物法术或法师的寒冰屏障法术).\\n\\n启用此选项将阻止您使用暴雪选项放置增益在目标框架上。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Show durability status*"', '"显示耐久状态*"'), 
    ('"If checked, your equipped item durability status will be shown when you hover over the expand button on the character sheet (bottom-right corner).\\n\\nIn addition, an overall percentage will be shown in the chat frame when you die.\\n\\n* Requires UI reload."', '"勾选： 当您的鼠标停留在角色属性窗口的额外按钮上时(右下角)会显示您的装备物品耐久度状态。\\n\\n此外，当您死的时候总百分比将显示在聊天框中。\\n\\n* 需要重载界面。."'), 
	#-------------------
    ('"Features"', '"功能"'), 
    ('"Manage frames*"', '"管理框架*"'), 
    ('"If checked, you will be able to change the position and scale of the player frame, target frame, world state, ghost frame and timer bar.  Your layout will be saved account-wide.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您将可以改变玩家框架、目标框架、世界状态、灵魂框架、计时条的位置与大小。 您的布局将会储存为帐号通用。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Class colored frames*"', '"框架职业颜色*"'), 
    ('"If checked, you will be able to show class coloring in the player frame, target frame and focus frame backgrounds.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您将能够在玩家框架、目标框架和焦点框架的背景显示职业颜色。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Show player chain*"', '"显示精英头像*"'), 
    ('"If checked, you will be able to show a rare, elite or rare elite chain around the player frame.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您的玩家头像可以显示为稀有、精英或稀有精英的头像。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Combat plates*"', '"战斗姓名板*"'), 
    ('"If checked, enemy nameplates will be shown automatically when you enter combat and hidden when combat ends.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：敌对姓名板将会自动在您进入战斗时显示并且离开战斗后隐藏。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Raid frame toggle*"', '"团队框架切换*"'), 
    ('"If checked, the button to toggle the raid container frame will be shown just above the raid management frame (left side of the screen) instead of in the raid management frame itself.\\n\\nThis allows you to toggle the raid container frame without needing to open the raid management frame.\\n\\n* Requires UI reload."', '"勾选：团队内容框架切换按钮将会显示在团队管理介面的上方(屏幕的左侧)并取代团队管理框架。\\n\\n这允许您切换团队内容框架而无需开启团队管理界面。\\n\\n* 需要重载界面。"'), 
    ('"Alerts"', '"警报"'), 
    ('"Hide loot alerts*"', '"隐藏战利品警报*"'), 
    ('"If checked, loot alerts will not be shown.\\n\\n* Requires UI reload."', '"勾选：战利品警报将不会显示。\\n\\n* 需要重载界面。"'), 
    ('"Hide garrison alerts*"', '"隐藏要塞警报*"'), 
    ('"If checked, mission, building and follower alerts will be shown in chat instead of an alert frame.\\n\\n* Requires UI reload."', '"勾选：追随者任务和要塞建筑的警报将会显示在聊天框，而不是一个警报框。\\n\\n* 需要重载界面。"'), 
    ('"Visibility"', '"可见"'), 
    ('"Hide gryphons*"', '"隐藏狮鹫兽*"'), 
    ('"If checked, the main bar gryphons will not be shown.\\n\\n* Requires UI reload."', '"勾选：在暴雪的主动作条的两边不会显示狮鹫兽。\\n\\n* 需要重载界面。"'), 
    ('"Hide stance bar*"', '"隐藏姿态条*"'), 
    ('"If checked, the stance bar will not be shown.\\n\\n* Requires UI reload."', '"勾选：姿态条将不显示。\\n\\n* 需要重载界面。"'), 
    ('"Hide character controls*"', '"隐藏角色控制*"'), 
    ('"If checked, control buttons (such as zoom) will not be shown at the top of the character frame, dressup frame and transmogrification frame.\\n\\n* Requires UI reload."', '"勾选：控制按钮(如缩放)不会显示在角色视窗的顶部、试装框架与塑型框架。\\n\\n* 需要重载界面。"'), 
    ('"Hide bodyguard gossip*"', '"隐藏保镖对话*"'), 
    ('"If checked, the gossip window will not be shown when you talk to an active garrison bodyguard.\\n\\nYou can hold the shift key down when you talk to a bodyguard to over-ride this setting.\\n\\n* Requires UI reload."', '"勾选：当您与一个已启用的要塞保镖对话时将不会出现谈话视窗。\\n\\n您可以在与保镖对谈时按下Shift键以暂停此设置。\\n\\n* 需要重载界面。"'), 
	#-------------------
    ('"Graphics"', '"图形"'), 
    ('"Disable shader effects*"', '"关闭着色器效果*"'), 
    ('"If checked, the screen glow effect, the death effect and special effects (such as invisibility) will be disabled.\\n\\nShader effects will be enabled automatically while using the S.E.L.F.I.E. camera.\\n\\nEnabling this option may increase your overall graphics performance and reduce nausea.\\n\\n* Requires UI reload."', '"勾选：屏幕的高亮效果、死亡效果与特殊效果(比如法师的隐形) 将被关闭。\\n\\n着色器效果将会在使用自拍神器时自动启用。\\n\\n启用此选项有可能增加您整体的绘图效能并减少不适感。\\n\\n* 需要重载界面。"'), 
    ('"Max camera distance*"', '"最大视野*"'), 
    ('"If checked, you will be able to zoom the camera out to a greater distance.\\n\\nEnabling this option will prevent you from changing the camera distance setting in the game options panel (Camera menu).\\n\\nIf you disable this option after previously enabling it, the camera zoom will reset the next time you zoom out with the mouse.\\n\\n* Requires UI reload."', '"勾选：视野将能够设定到更远的距离。\\n\\n启用该选项将禁止您更改在游戏选项面板中的最大镜头距离(镜头菜单)。\\n\\n如果您之前启用后禁用此选项，在下一次鼠标缩小视野时视野将复位。\\n\\n* 需要重载界面。"'), 
    ('"Enable viewport*"', '"启用窗口背景*"'), 
    ('"If checked, you will be able to create a viewport.  A viewport adds adjustable black borders around the game world.\\n\\nThe borders are placed on top of the game world but under the UI so you can place UI elements over them.\\n\\n* Requires UI reload.  After the reload, a configuration button will be available to the right."', '"勾选：您可以创造一个窗口背景。窗口背景增加一个可调的黑色边框包覆游戏世界。\\n\\n此边框放置在游戏世界的上方但会在界面的下层，所以您可以放置界面的元素在它上面。\\n\\n此外，您将能够如您所愿的调整游戏世界来适应边框的顶部和底部。\\n\\n* 需要重载界面。 重载之后，右侧的配置按钮才能使用。"'), 
    ('"Sound"', '"音效"'), 
    ('"Silence rested emotes*"', '"休息时表情静音*"'), 
    ("If checked, emote sounds will be silenced while your character is:\\n\\n- resting\\n- at the Hathill Market\\n- at the Grim Guzzler\\n\\nEmote sounds will be enabled when none of the above apply.\\n\\n* Requires UI reload.", "勾选：表情音效将静音当您的角色处于:\\n\\n- 休息状态\\n- 在半丘市集\\n- 在黑铁酒吧\\n\\n当不符合上述场合时会启用表情音效。\\n\\n* 需要重载界面"), 
    ('"Game Options"', '"游戏选项"'), 
    ('"Lockout sharing*"', '"锁定共享*"'), 
    ("If checked, the 'Display only character achievements to others' setting in the game options panel (Display menu) will be permanently checked and locked.\\n\\nThis option is useful if you always wish for the game options panel setting to be enabled for every character.\\n\\nNote that changes to the game options panel setting will be updated on the armory only after you logout of the game.\\n\\n* Requires UI reload.", "勾选：游戏选项面板中“对他人只显示角色成就”设置(显示菜单) 将永久勾选并锁定。\\n\\n如果您希望在游戏选项面板为每个角色总是启用设置，此选项很有用的。\\n\\n注意更改游戏选项面板设置将只有在您退出游戏之后更新英雄榜。\\n\\n* 需要重载界面。"), 
    ('"Show character addons*"', '"显示角色插件*"'), 
    ('"If checked, the addon list (accessible from the game menu) will show character based addons by default.\\n\\n* Requires UI reload."', '"勾选：默认情况下插件列表(可以通过游戏菜单)将显示角色基础插件。\\n\\n* 需要重载界面。"'), 
    ('"Remove raid restrictions*"', '"移除团队限制*"'), 
    ('"If checked, your low level characters will be allowed to join raid groups.\\n\\nNote that you cannot join a raid group directly with a low level character.  You have to join a party group first then the party leader should convert the party group to a raid group.\\n\\nReload your UI if the group leader is unable to convert the party group to a raid group.\\n\\n* Requires UI reload."', '"勾选：您的低等级的人物将可以加入团队。\\n\\n注意您无法直接用一个低等级的角色直接加入团队。您必须先加入一个小队然后领队才将队伍转化为团队。\\n\\n如果领队无法将队伍转化为团队，您需要重载您的界面。\\n\\n* 需要重载界面。"'), 
    ('"Disable loot warnings"', '"禁用拾取确认"'), 
    ('"If checked, confirmations which appear when you choose a loot roll option (need, greed or disenchant) will not be shown."', '"勾选：当您选择一个掷骰选项时(需求, 贪婪或分解)的确认信息将不会显示。"'), 
    ('"Disable map emote*"', '"禁用地图表情*"'), 
    ('"If checked, your character will not perform the reading emote when you open the map.\\n\\n* Requires UI reload."', '"勾选：当您打开地图时，您的角色将不会进行阅读表情。\\n\\n* 需要重载界面。"'), 
    ('"Skip cinematics*"', '"跳过过场动画*"'), 
    ('"If checked, in-game cinematics will be skipped if at all possible.\\n\\nYou can hold the shift key down when a cinematic is about to start to over-ride this setting.\\n\\nNote that some cinematics cannot be skipped.\\n\\n* Requires UI reload."', '"勾选：如有可能，在游戏中过场动画会被跳过。\\n\\n当过场动画即将开始时，您可以按住shift键暂停此设置。\\n\\n请注意，某些过场动画不能被跳过。\\n\\n* 需要重载界面。"'), 
	#-------------------
    ('"Show minimap button*"', '"显示小地图按钮*"'), 
    ("If checked, a minimap button will be available.\\n\\nNote that if you disable this option, you will only be able to access the options panel by entering '/run leatrix()'.\\n\\nLeft-click - Toggle options.\\n\\nRight-click - Toggle errors (if enabled, red while showing).\\n\\nSHIFT/Left-click - Toggle music.\\n\\nSHIFT/Right-click - Toggle coordinates (if enabled).\\n\\nCTRL/Left-click - Toggle minimap target tracking.\\n\\nCTRL/SHIFT/Left-click - Toggle Zygor (if installed).\\n\\nCTRL/SHIFT/Right-click - Toggle windowed mode.\\n\\n* Requires UI reload.", "勾选：显示一个小地图按钮。\\n\\n请注意，如果禁用此选项，您想进入选项面板只能通过输入 '/run leatrix()'.\\n\\n左键点击 - 切换选项。\\n\\n右键点击 - 切换红字 (如果已启用，显示红色)。\\n\\nSHIFT+左键点击 - 切换音乐。\\n\\nSHIFT+右键点击 - 切换坐标 (如果已启用)。\\n\\nCTRL+左键点击 - 切换小地图的目标追踪。\\n\\nCTRL+SHIFT+左键点击 - 切换Zygor(如果已安装)。\\n\\nCTRL+SHIFT+右键点击 - 切换窗口模式。\\n\\n* 需要重载界面。"), 
    ('"Show startup message"', '"显示启始信息"'), 
    ('"If checked, the addon name and version will be shown in chat when you login or reload your UI."', '"勾选：当您登入或重载界面的时候，插件的名称与版本将显示在聊天视窗。"'), 
    ('"Show option tooltips"', '"显示选项提示"'), 
    ("If checked, tooltips will be shown for all of the checkboxes and buttons in the options panel.\\n\\nIf unchecked, no tooltips will be shown and the configuration panel help buttons will be unavailable.\\n\\nIt's recommended that you leave this option checked.", "勾选：在Leatrix Plus所有的复选框和按钮上将显示提示。\\n\\n未选：不会显示提示并且配置面板的帮助按钮将不可用。\\n\\n建议您启用这个选项。"), 
    ('"Panel Alpha"', '"面板透明度"'), 
    ('"Modify panel alpha"', '"修改面板透明度"'), 
    ('"If checked, you will be able to change the alpha (transparency) of the options panel.  If unchecked, the normal alpha will be used."', '"勾选：您可以改变面板的透明度。未选：使用正常的透明度。"'), 
    ('"Panel Scale"', '"面板大小"'), 
    ('"Modify panel scale"', '"修改面板大小"'), 
    ('"If checked, you will be able to change the scale of the options panel.  If unchecked, the normal scale will be used."', '"勾选：您可以改变面板的大小。 未选：使用正常的大小。"'), 

]
ReplaceFunc(findReplacePairs);
